export interface Video{
    id:string,
    title:string,
    description:string,
    publicId: string,
    originalUrl: string,
    transformedUrl:string,
    originalSize:string,
    compressedSize : string,
    duration: number,
    prompt: string, 
    numInferenceSteps: number, 
    seed: number ,
    proMode: boolean,
    aspectRatio: string,
    resolution: string,
    numFrames: number ,
    enableSafetyChecker: boolean ,
    strength:number ,    
    createdAt: Date, 
    updatedAt: Date
}